#To change the port no
#server:
#  port: 3000
# to disable the web server
#spring:
#  main:
#    web-application-type: none
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
aws:
  region: us-east-2
  s3:
    mock: true
    buckets:
      customer: fs-adekunle-customer-test
server:
  error:
    include-message: always
  port: 8080
spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: amigoscode
    password: password
  jpa:
    hibernate:
#      ddl-auto: create-drop
#      ddl-auto: none
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB

# for Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health, info"