#To change the port no
#server:
#  port: 3000
# to disable the web server
#spring:
#  main:
#    web-application-type: none
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
server:
  error:
    include-message: always
  port: 8080
spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://awseb-e-psmh9yvtve-stack-awsebrdsdatabase-cwj2zgwhrxl5.cqfld9zlmnkq.us-east-2.rds.amazonaws.com:5432/customer
    username: amigoscode
    password: password
  jpa:
    hibernate:
      #      ddl-auto: create-drop
      #      ddl-auto: none
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
# for Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health, info"